services:
  rabbitmq:
    container_name: rabbitmq
    image: 'rabbitmq:management'
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBIT_PASS}
    ports:
      - '5672:5672'
      - '15672:15672'
      - '61613:61613'
    command: ["sh", "-c", "rabbitmq-plugins enable rabbitmq_stomp && rabbitmq-server"]