spring:
  profiles:
    active:
      - dev
    group:
      local:
        - local
        - jwt
        - oauth
        - rabbitmq
      dev:
        - dev
        - jwt
        - oauth
        - rabbitmq